name = "LazyModules"
uuid = "8cdb02fc-e678-4876-92c5-9defec4f444e"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test=["SparseArrays", "Test"]
